name: social_media_application
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  flutter_signin_button: ^1.0.0
  flutter_spinkit: ^4.1.2+1
  outline_material_icons: ^0.1.0
  timeago: ^2.0.14
  carousel_slider: ^2.2.1
  cupertino_icons: ^0.1.2
  settings_ui: ^0.3.0
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.15
  dio: ^3.0.9
  fluttertoast: ^5.0.1
  shared_preferences: ^0.5.7+3
  google_sign_in: ^4.5.1
  image_picker: ^0.6.7+4
  cached_network_image: ^2.2.0+1
  multi_image_picker: ^4.6.7
  image_cropper: ^1.2.3
  flutter_absolute_path: ^1.0.6
  carousel_pro: ^1.0.0
  font_awesome_flutter: ^8.8.1
  line_awesome_flutter: ^1.0.1
  meet_network_image: ^0.1.2
  photo_view: ^0.9.2
  getwidget: ^1.1.0
  optimized_cached_image: ^0.1.14
  dash_chat: ^1.1.13
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  uuid: ^2.2.0
  firebase_auth: ^0.16.1
  progress_dialog: ^1.2.4
  date_time_format: ^1.0.0+4
  like_button: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '^0.7.2'

flutter:
  uses-material-design: true
  assets:
    - assets/default.jpg
    - assets/images/
  fonts:
    - family: FlutterIcons
      fonts:
        - asset: assets/fonts/FlutterIcons.ttf

    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
